In [1637]:
import os
import random
import numpy as np
import pickle as pkl
import scipy.sparse as sp
import sys
from tqdm import tqdm

In [1638]:
with open("data/ind.question1_sub_bal.ty", 'rb') as f:    
    y_true = pkl.load(f)

In [1639]:
y_true = np.argmax(y_true, axis=1)

In [1640]:
y_true

array([0, 0, 1, ..., 0, 0, 1])

In [1641]:
y_pred = np.loadtxt("gnn_pred2_win4.csv")

In [1642]:
y_pred

array([0., 0., 1., ..., 0., 0., 1.])

In [1643]:
ind_short = np.loadtxt("short_sents.txt").astype(np.int)

In [1644]:
ind_short

array([   0,    1,    2, ..., 9985, 9992, 9993])

In [1645]:
y_true_short = y_true[ind_short]

In [1646]:
y_true_short.shape

(4756,)

In [1647]:
y_pred_short = y_pred[ind_short]

In [1648]:
ind_medium = np.loadtxt("medium_sents.txt").astype(np.int)

In [1649]:
y_true_medium = y_true[ind_medium]

In [1650]:
y_pred_medium = y_pred[ind_medium]

In [1651]:
ind_long = np.loadtxt("long_sents.txt").astype(np.int)

In [1652]:
y_true_long = y_true[ind_long]

In [1653]:
y_pred_long = y_pred[ind_long]

In [1654]:
ind_mixed = np.loadtxt("unmatched_len.txt").astype(np.int)

In [1655]:
y_true_mixed = y_true[ind_mixed]

In [1656]:
y_pred_mixed = y_pred[ind_mixed]

In [1657]:
ind_inductive = np.loadtxt("inductive_ind.txt").astype(np.int)

In [1658]:
y_true_inductive = y_true[ind_inductive]

In [1659]:
y_pred_inductive = y_pred[ind_inductive]

In [1660]:
y_true_n_inductive = y_true[[i for i in range(9999) if i not in ind_inductive]]

In [1661]:
y_pred_n_inductive = y_pred[[i for i in range(9999) if i not in ind_inductive]]

In [1662]:
from sklearn import metrics

In [1663]:
print(metrics.classification_report(y_true_short, y_pred_short, digits=4))

              precision    recall  f1-score   support

           0     0.8891    0.7244    0.7983      2910
           1     0.6637    0.8575    0.7483      1846

    accuracy                         0.7761      4756
   macro avg     0.7764    0.7910    0.7733      4756
weighted avg     0.8016    0.7761    0.7789      4756



In [1664]:
print(metrics.classification_report(y_true_medium, y_pred_medium, digits=4))

              precision    recall  f1-score   support

           0     0.9066    0.7430    0.8167      1490
           1     0.6749    0.8746    0.7619       909

    accuracy                         0.7928      2399
   macro avg     0.7908    0.8088    0.7893      2399
weighted avg     0.8188    0.7928    0.7959      2399



In [1665]:
print(metrics.classification_report(y_true_long, y_pred_long, digits=4))

              precision    recall  f1-score   support

           0     0.9167    0.7857    0.8462        14
           1     0.6667    0.8571    0.7500         7

    accuracy                         0.8095        21
   macro avg     0.7917    0.8214    0.7981        21
weighted avg     0.8333    0.8095    0.8141        21



In [1666]:
print(metrics.classification_report(y_true_mixed, y_pred_mixed, digits=4))

              precision    recall  f1-score   support

           0     0.8962    0.7536    0.8187      1798
           1     0.6608    0.8461    0.7420      1020

    accuracy                         0.7871      2818
   macro avg     0.7785    0.7998    0.7804      2818
weighted avg     0.8110    0.7871    0.7910      2818



In [1667]:
print(metrics.classification_report(y_true_inductive, y_pred_inductive, digits=4))

              precision    recall  f1-score   support

           0     0.8826    0.7368    0.8031       969
           1     0.6764    0.8487    0.7528       628

    accuracy                         0.7808      1597
   macro avg     0.7795    0.7928    0.7780      1597
weighted avg     0.8015    0.7808    0.7834      1597



In [1668]:
print(metrics.classification_report(y_true_n_inductive, y_pred_n_inductive, digits=4))

              precision    recall  f1-score   support

           0     0.8979    0.7377    0.8100      5246
           1     0.6637    0.8606    0.7494      3156

    accuracy                         0.7839      8402
   macro avg     0.7808    0.7991    0.7797      8402
weighted avg     0.8099    0.7839    0.7872      8402



In [1669]:
print(metrics.classification_report(y_true, y_pred, digits=4))

              precision    recall  f1-score   support

           0     0.8955    0.7376    0.8089      6215
           1     0.6658    0.8586    0.7500      3784

    accuracy                         0.7834      9999
   macro avg     0.7806    0.7981    0.7794      9999
weighted avg     0.8086    0.7834    0.7866      9999



In [1670]:
y_true_short.shape, y_true_medium.shape, y_true_long.shape, y_true_mixed.shape, y_true.shape

((4756,), (2399,), (21,), (2818,), (9999,))

In [1671]:
ind_inductive

array([   9,   24,   28, ..., 9995, 9997, 9998])

In [1672]:
ind_short, ind_medium, ind_long, ind_mixed

(array([   0,    1,    2, ..., 9985, 9992, 9993]),
 array([   4,    5,   13, ..., 9988, 9989, 9991]),
 array([   7,  306,  790,  795, 1408, 1970, 2362, 3235, 3238, 3260, 3316,
        5128, 5175, 5585, 8165, 8171, 8274, 8497, 8604, 9424, 9779]),
 array([   6,    8,   16, ..., 9981, 9983, 9990]))

In [1673]:
y_pred_gnn = np.loadtxt("gnn_pred4_win4.csv")

In [1674]:
y_pred_dnn = np.loadtxt("dnn_pred.csv")

In [1675]:
indices = np.where(y_pred_gnn != y_pred_dnn)[0]

In [1676]:
y_pred_gnn_dif = y_pred_gnn[indices]

In [1677]:
y_pred_dnn_dif = y_pred_dnn[indices]

In [1678]:
y_true_diff = y_true[indices]

In [1679]:
print(metrics.classification_report(y_true_diff, y_pred_gnn_dif, digits=4))

              precision    recall  f1-score   support

           0     0.6991    0.6900    0.6945      1145
           1     0.2843    0.2931    0.2886       481

    accuracy                         0.5726      1626
   macro avg     0.4917    0.4915    0.4916      1626
weighted avg     0.5764    0.5726    0.5744      1626



In [1680]:
print(metrics.classification_report(y_true_diff, y_pred_dnn_dif, digits=4))

              precision    recall  f1-score   support

           0     0.7157    0.3100    0.4327      1145
           1     0.3009    0.7069    0.4221       481

    accuracy                         0.4274      1626
   macro avg     0.5083    0.5085    0.4274      1626
weighted avg     0.5930    0.4274    0.4295      1626



In [1681]:
np.where(y_pred_gnn_dif == y_true_diff)[0].shape

(931,)

In [1682]:
np.where(y_pred_dnn_dif == y_true_diff)[0]

array([   0,    2,    5,    8,    9,   10,   11,   12,   13,   18,   19,
         22,   23,   24,   25,   26,   27,   31,   34,   36,   38,   39,
         40,   41,   42,   43,   45,   46,   47,   50,   52,   55,   60,
         61,   62,   64,   65,   69,   70,   73,   75,   77,   78,   83,
         84,   85,   87,   88,   90,   92,   94,   98,   99,  100,  106,
        107,  108,  109,  110,  111,  114,  117,  123,  126,  128,  129,
        131,  132,  133,  135,  137,  139,  141,  142,  145,  146,  152,
        153,  158,  161,  162,  166,  169,  170,  175,  177,  178,  179,
        182,  183,  184,  186,  189,  191,  194,  196,  197,  200,  201,
        203,  204,  207,  212,  216,  221,  222,  223,  225,  226,  228,
        232,  233,  239,  241,  249,  254,  264,  267,  268,  269,  271,
        272,  273,  277,  282,  283,  284,  285,  286,  287,  288,  290,
        294,  295,  296,  298,  299,  300,  303,  304,  307,  309,  312,
        313,  314,  315,  317,  322,  326,  327,  3

In [1683]:
indices

array([  16,   23,   29, ..., 9987, 9990, 9994])

In [1684]:
gnn_right = np.where(y_pred_gnn == y_true)[0]

In [1685]:
dnn_right = np.where(y_pred_dnn == y_true)[0]

In [1686]:
np.savetxt('indices_gnn_right.txt', np.intersect1d(indices, gnn_right), delimiter=',')

In [1687]:
np.savetxt('indices_dnn_right.txt', np.intersect1d(indices, dnn_right), delimiter=',')